#!/bin/bash
 

echo -n "enter your name: "
read name
echo -n "enter you age: "
read age
if [ $age -gt 18 ]
then
    echo  "$name  eligible to vote"   
    1>>correct.lst
else
    echo  "$name not elligible to vote" >> not-ok.lst
fi